
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AdminPageFilter': typeof import("../src/components/AdminPage/Filter/Filter.vue")['default']
    'AdminPageFilterTabFilter': typeof import("../src/components/AdminPage/Filter/TabFilter.vue")['default']
    'AdminPageMobileSidebar': typeof import("../src/components/AdminPage/MobileSidebar.vue")['default']
    'AdminPageProductTable': typeof import("../src/components/AdminPage/Product/Table.vue")['default']
    'AdminPageSidebar': typeof import("../src/components/AdminPage/Sidebar.vue")['default']
    'AdminPageTopbar': typeof import("../src/components/AdminPage/Topbar.vue")['default']
    'AutoLogOut': typeof import("../src/components/AutoLogOut.vue")['default']
    'BaseInput': typeof import("../src/components/BaseInput.vue")['default']
    'ButtonTimePicker': typeof import("../src/components/Button/TimePicker.vue")['default']
    'Captcha': typeof import("../src/components/Captcha/Captcha.vue")['default']
    'ChartBarchart': typeof import("../src/components/Chart/Barchart.vue")['default']
    'ChartDoughnutChart': typeof import("../src/components/Chart/DoughnutChart.vue")['default']
    'ChartLineChart': typeof import("../src/components/Chart/LineChart.vue")['default']
    'Child': typeof import("../src/components/Child.vue")['default']
    'Dialog': typeof import("../src/components/Dialog/Dialog.vue")['default']
    'FormsPayment': typeof import("../src/components/Forms/Payment.vue")['default']
    'GraphBarChart': typeof import("../src/components/Graph/BarChart.vue")['default']
    'GraphBaseChart': typeof import("../src/components/Graph/BaseChart.vue")['default']
    'GraphDoughnutChart': typeof import("../src/components/Graph/DoughnutChart.vue")['default']
    'GraphLineChart': typeof import("../src/components/Graph/LineChart.vue")['default']
    'GraphPieChart': typeof import("../src/components/Graph/PieChart.vue")['default']
    'GridsLight': typeof import("../src/components/GridsLight.vue")['default']
    'Navbar': typeof import("../src/components/Navbar.vue")['default']
    'Onmounted': typeof import("../src/components/Onmounted.vue")['default']
    'Product': typeof import("../src/components/Product.vue")['default']
    'SkuProduct': typeof import("../src/components/SkuProduct/SkuProduct.vue")['default']
    'TableLoad': typeof import("../src/components/TableLoad.vue")['default']
    'TablesTable1': typeof import("../src/components/Tables/Table1.vue")['default']
    'TablesTable2': typeof import("../src/components/Tables/Table2.vue")['default']
    'TablesTable3': typeof import("../src/components/Tables/Table3.vue")['default']
    'UploadFileInput': typeof import("../src/components/UploadFile/Input.vue")['default']
    'UploadFileMultiFile': typeof import("../src/components/UploadFile/MultiFile.vue")['default']
    'UploadFileSingleFile': typeof import("../src/components/UploadFile/SingleFile.vue")['default']
    'Watch': typeof import("../src/components/Watch.vue")['default']
    'WatchCompute': typeof import("../src/components/WatchCompute.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAdminPageFilter': typeof import("../src/components/AdminPage/Filter/Filter.vue")['default']
    'LazyAdminPageFilterTabFilter': typeof import("../src/components/AdminPage/Filter/TabFilter.vue")['default']
    'LazyAdminPageMobileSidebar': typeof import("../src/components/AdminPage/MobileSidebar.vue")['default']
    'LazyAdminPageProductTable': typeof import("../src/components/AdminPage/Product/Table.vue")['default']
    'LazyAdminPageSidebar': typeof import("../src/components/AdminPage/Sidebar.vue")['default']
    'LazyAdminPageTopbar': typeof import("../src/components/AdminPage/Topbar.vue")['default']
    'LazyAutoLogOut': typeof import("../src/components/AutoLogOut.vue")['default']
    'LazyBaseInput': typeof import("../src/components/BaseInput.vue")['default']
    'LazyButtonTimePicker': typeof import("../src/components/Button/TimePicker.vue")['default']
    'LazyCaptcha': typeof import("../src/components/Captcha/Captcha.vue")['default']
    'LazyChartBarchart': typeof import("../src/components/Chart/Barchart.vue")['default']
    'LazyChartDoughnutChart': typeof import("../src/components/Chart/DoughnutChart.vue")['default']
    'LazyChartLineChart': typeof import("../src/components/Chart/LineChart.vue")['default']
    'LazyChild': typeof import("../src/components/Child.vue")['default']
    'LazyDialog': typeof import("../src/components/Dialog/Dialog.vue")['default']
    'LazyFormsPayment': typeof import("../src/components/Forms/Payment.vue")['default']
    'LazyGraphBarChart': typeof import("../src/components/Graph/BarChart.vue")['default']
    'LazyGraphBaseChart': typeof import("../src/components/Graph/BaseChart.vue")['default']
    'LazyGraphDoughnutChart': typeof import("../src/components/Graph/DoughnutChart.vue")['default']
    'LazyGraphLineChart': typeof import("../src/components/Graph/LineChart.vue")['default']
    'LazyGraphPieChart': typeof import("../src/components/Graph/PieChart.vue")['default']
    'LazyGridsLight': typeof import("../src/components/GridsLight.vue")['default']
    'LazyNavbar': typeof import("../src/components/Navbar.vue")['default']
    'LazyOnmounted': typeof import("../src/components/Onmounted.vue")['default']
    'LazyProduct': typeof import("../src/components/Product.vue")['default']
    'LazySkuProduct': typeof import("../src/components/SkuProduct/SkuProduct.vue")['default']
    'LazyTableLoad': typeof import("../src/components/TableLoad.vue")['default']
    'LazyTablesTable1': typeof import("../src/components/Tables/Table1.vue")['default']
    'LazyTablesTable2': typeof import("../src/components/Tables/Table2.vue")['default']
    'LazyTablesTable3': typeof import("../src/components/Tables/Table3.vue")['default']
    'LazyUploadFileInput': typeof import("../src/components/UploadFile/Input.vue")['default']
    'LazyUploadFileMultiFile': typeof import("../src/components/UploadFile/MultiFile.vue")['default']
    'LazyUploadFileSingleFile': typeof import("../src/components/UploadFile/SingleFile.vue")['default']
    'LazyWatch': typeof import("../src/components/Watch.vue")['default']
    'LazyWatchCompute': typeof import("../src/components/WatchCompute.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminPageFilter: typeof import("../src/components/AdminPage/Filter/Filter.vue")['default']
export const AdminPageFilterTabFilter: typeof import("../src/components/AdminPage/Filter/TabFilter.vue")['default']
export const AdminPageMobileSidebar: typeof import("../src/components/AdminPage/MobileSidebar.vue")['default']
export const AdminPageProductTable: typeof import("../src/components/AdminPage/Product/Table.vue")['default']
export const AdminPageSidebar: typeof import("../src/components/AdminPage/Sidebar.vue")['default']
export const AdminPageTopbar: typeof import("../src/components/AdminPage/Topbar.vue")['default']
export const AutoLogOut: typeof import("../src/components/AutoLogOut.vue")['default']
export const BaseInput: typeof import("../src/components/BaseInput.vue")['default']
export const ButtonTimePicker: typeof import("../src/components/Button/TimePicker.vue")['default']
export const Captcha: typeof import("../src/components/Captcha/Captcha.vue")['default']
export const ChartBarchart: typeof import("../src/components/Chart/Barchart.vue")['default']
export const ChartDoughnutChart: typeof import("../src/components/Chart/DoughnutChart.vue")['default']
export const ChartLineChart: typeof import("../src/components/Chart/LineChart.vue")['default']
export const Child: typeof import("../src/components/Child.vue")['default']
export const Dialog: typeof import("../src/components/Dialog/Dialog.vue")['default']
export const FormsPayment: typeof import("../src/components/Forms/Payment.vue")['default']
export const GraphBarChart: typeof import("../src/components/Graph/BarChart.vue")['default']
export const GraphBaseChart: typeof import("../src/components/Graph/BaseChart.vue")['default']
export const GraphDoughnutChart: typeof import("../src/components/Graph/DoughnutChart.vue")['default']
export const GraphLineChart: typeof import("../src/components/Graph/LineChart.vue")['default']
export const GraphPieChart: typeof import("../src/components/Graph/PieChart.vue")['default']
export const GridsLight: typeof import("../src/components/GridsLight.vue")['default']
export const Navbar: typeof import("../src/components/Navbar.vue")['default']
export const Onmounted: typeof import("../src/components/Onmounted.vue")['default']
export const Product: typeof import("../src/components/Product.vue")['default']
export const SkuProduct: typeof import("../src/components/SkuProduct/SkuProduct.vue")['default']
export const TableLoad: typeof import("../src/components/TableLoad.vue")['default']
export const TablesTable1: typeof import("../src/components/Tables/Table1.vue")['default']
export const TablesTable2: typeof import("../src/components/Tables/Table2.vue")['default']
export const TablesTable3: typeof import("../src/components/Tables/Table3.vue")['default']
export const UploadFileInput: typeof import("../src/components/UploadFile/Input.vue")['default']
export const UploadFileMultiFile: typeof import("../src/components/UploadFile/MultiFile.vue")['default']
export const UploadFileSingleFile: typeof import("../src/components/UploadFile/SingleFile.vue")['default']
export const Watch: typeof import("../src/components/Watch.vue")['default']
export const WatchCompute: typeof import("../src/components/WatchCompute.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAdminPageFilter: typeof import("../src/components/AdminPage/Filter/Filter.vue")['default']
export const LazyAdminPageFilterTabFilter: typeof import("../src/components/AdminPage/Filter/TabFilter.vue")['default']
export const LazyAdminPageMobileSidebar: typeof import("../src/components/AdminPage/MobileSidebar.vue")['default']
export const LazyAdminPageProductTable: typeof import("../src/components/AdminPage/Product/Table.vue")['default']
export const LazyAdminPageSidebar: typeof import("../src/components/AdminPage/Sidebar.vue")['default']
export const LazyAdminPageTopbar: typeof import("../src/components/AdminPage/Topbar.vue")['default']
export const LazyAutoLogOut: typeof import("../src/components/AutoLogOut.vue")['default']
export const LazyBaseInput: typeof import("../src/components/BaseInput.vue")['default']
export const LazyButtonTimePicker: typeof import("../src/components/Button/TimePicker.vue")['default']
export const LazyCaptcha: typeof import("../src/components/Captcha/Captcha.vue")['default']
export const LazyChartBarchart: typeof import("../src/components/Chart/Barchart.vue")['default']
export const LazyChartDoughnutChart: typeof import("../src/components/Chart/DoughnutChart.vue")['default']
export const LazyChartLineChart: typeof import("../src/components/Chart/LineChart.vue")['default']
export const LazyChild: typeof import("../src/components/Child.vue")['default']
export const LazyDialog: typeof import("../src/components/Dialog/Dialog.vue")['default']
export const LazyFormsPayment: typeof import("../src/components/Forms/Payment.vue")['default']
export const LazyGraphBarChart: typeof import("../src/components/Graph/BarChart.vue")['default']
export const LazyGraphBaseChart: typeof import("../src/components/Graph/BaseChart.vue")['default']
export const LazyGraphDoughnutChart: typeof import("../src/components/Graph/DoughnutChart.vue")['default']
export const LazyGraphLineChart: typeof import("../src/components/Graph/LineChart.vue")['default']
export const LazyGraphPieChart: typeof import("../src/components/Graph/PieChart.vue")['default']
export const LazyGridsLight: typeof import("../src/components/GridsLight.vue")['default']
export const LazyNavbar: typeof import("../src/components/Navbar.vue")['default']
export const LazyOnmounted: typeof import("../src/components/Onmounted.vue")['default']
export const LazyProduct: typeof import("../src/components/Product.vue")['default']
export const LazySkuProduct: typeof import("../src/components/SkuProduct/SkuProduct.vue")['default']
export const LazyTableLoad: typeof import("../src/components/TableLoad.vue")['default']
export const LazyTablesTable1: typeof import("../src/components/Tables/Table1.vue")['default']
export const LazyTablesTable2: typeof import("../src/components/Tables/Table2.vue")['default']
export const LazyTablesTable3: typeof import("../src/components/Tables/Table3.vue")['default']
export const LazyUploadFileInput: typeof import("../src/components/UploadFile/Input.vue")['default']
export const LazyUploadFileMultiFile: typeof import("../src/components/UploadFile/MultiFile.vue")['default']
export const LazyUploadFileSingleFile: typeof import("../src/components/UploadFile/SingleFile.vue")['default']
export const LazyWatch: typeof import("../src/components/Watch.vue")['default']
export const LazyWatchCompute: typeof import("../src/components/WatchCompute.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
